version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.25.2
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD44328-if00:/dev/ttyACM0
    restart: always
    ports:
      - 8082:8080
#    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Moscow

