version: '3'

networks:
  traefik:
    external: true

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.33.0
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      #      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD44328-if00:/dev/ttyACM0
      - /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0:/dev/ttyACM0
    restart: always
    privileged: true
    networks:
      - traefik
    environment:
      - TZ=Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.zigbee2mqtt-secure.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.zigbee2mqtt-secure.tls.certresolver=default"
      - "traefik.http.routers.zigbee2mqtt-secure.service=zigbee2mqtt"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"

